### ISSUE TITLE
Договор на сиденья

### ISSUE THREAD

**Issue by lkurakht** [lkurakht/reg_motorhome#1]
Заполни, пожалуйста, свои паспортные данные.

**Comment by asavan** [comment]
![image](https://user-images.githubusercontent.com/2963430/97674703-07540080-1a9f-11eb-9636-9c0b1e474344.png)
![image](https://user-images.githubusercontent.com/2963430/97674751-15098600-1a9f-11eb-952b-0e70edeb0633.png)
